-- PATCH: 1

CREATE TABLE Test (
    Id UNIQUEIDENTIFIER NOT NULL ROWGUIDCOL CONSTRAINT DF_Test_Id DEFAULT (newid()),
    RecordVersion ROWVERSION,
	RecordCreatedAt DATETIMEOFFSET NOT NULL CONSTRAINT DF_Test_RecordCreatedAt DEFAULT (getutcdate()),
	RecordUpdatedAt DATETIMEOFFSET NOT NULL CONSTRAINT DF_Test_RecordUpdatedAt DEFAULT (getutcdate()),
	Etag NVARCHAR(MAX) NOT NULL,

	ParentId UNIQUEIDENTIFIER NULL CONSTRAINT Fk_Test_ParentId REFERENCES Test ON DELETE NO ACTION ON UPDATE NO ACTION,
	Name NVARCHAR(1024) NOT NULL,
	Description NVARCHAR(MAX) NULL,
	FinishedAt DATETIMEOFFSET NULL,
	State INTEGER NOT NULL,
	StateMessage NVARCHAR(MAX) NULL,
	PropertiesJson NVARCHAR(MAX) NULL,

    CONSTRAINT PK_Test PRIMARY KEY NONCLUSTERED (Id)
)

CREATE CLUSTERED INDEX IX_Test_RecordCreatedAt ON Test (RecordCreatedAt)
CREATE INDEX IX_Test_ParentId ON Test (ParentId)
